#!/usr/bin/env python3
"""Generate CHUÍ's deterministic synthetic SSP v2 validation table.

The numbers are deliberately synthetic and are not a production yield model.
They exist only to exercise interpolation, interval additivity, delayed channels,
restart bookkeeping, and conservative deposition without inventing astrophysical
calibration constants.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

AGES_YR = (0.0, 3.0e6, 1.0e7, 1.0e8, 1.0e9, 1.4e10)
METALLICITIES = (0.0, 0.01, 0.03)

RETURN = {
    "winds_agb": (0.0, 0.01, 0.04, 0.08, 0.14, 0.20),
    "ccsn": (0.0, 0.00, 0.05, 0.07, 0.07, 0.07),
    "snia": (0.0, 0.00, 0.00, 0.003, 0.02, 0.08),
}
NEW_METALS = {
    "winds_agb": (0.0, 1.0e-4, 4.0e-4, 1.0e-3, 1.5e-3, 2.0e-3),
    "ccsn": (0.0, 0.0, 2.0e-3, 4.0e-3, 4.0e-3, 4.0e-3),
    "snia": (0.0, 0.0, 0.0, 2.0e-4, 1.5e-3, 5.0e-3),
}
EVENTS = {
    "winds_agb": (0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    "ccsn": (0.0, 0.0, 8.0e-3, 1.0e-2, 1.0e-2, 1.0e-2),
    "snia": (0.0, 0.0, 0.0, 1.0e-4, 8.0e-4, 2.0e-3),
}
ENERGY_ERG_PER_MASS_CODE = {
    "winds_agb": (0.0, 1.0e45, 5.0e45, 2.0e46, 4.0e46, 6.0e46),
    "ccsn": (0.0, 0.0, 8.0e48, 1.0e49, 1.0e49, 1.0e49),
    "snia": (0.0, 0.0, 0.0, 1.0e47, 8.0e47, 2.0e48),
}
CHANNELS = ("winds_agb", "ccsn", "snia")


def format_row(values: list[float]) -> str:
    return " ".join(f"{value:.17e}" for value in values)


def build_payload() -> str:
    rows: list[str] = []
    for metallicity in METALLICITIES:
        for age_index, age in enumerate(AGES_YR):
            returned_channel = [RETURN[name][age_index] for name in CHANNELS]
            new_channel = [NEW_METALS[name][age_index] for name in CHANNELS]
            total_metals_channel = [
                returned_channel[i] * metallicity + new_channel[i]
                for i in range(len(CHANNELS))
            ]
            events_channel = [EVENTS[name][age_index] for name in CHANNELS]
            energy_channel = [ENERGY_ERG_PER_MASS_CODE[name][age_index] for name in CHANNELS]
            returned = sum(returned_channel)
            total_metals = sum(total_metals_channel)
            new_metals = sum(new_channel)
            events = sum(events_channel)
            energy = sum(energy_channel)
            values = [
                metallicity,
                age,
                returned,
                total_metals,
                new_metals,
                events,
                energy,
                *returned_channel,
                *total_metals_channel,
                *new_channel,
                *events_channel,
                *energy_channel,
            ]
            rows.append(format_row(values))
    return "\n".join(rows) + "\n"


def render() -> str:
    payload = build_payload()
    payload_sha256 = hashlib.sha256(payload.encode("utf-8")).hexdigest()
    header = f"""# table_id = chui_synthetic_ssp_validation
# table_version = v2_test_2026_08
# source_papers = none; deterministic synthetic validation data
# source_repository = generated by tools/generate_stellar_evolution_test_table.py
# redistribution_license = CC0-1.0
# sha256 = {payload_sha256}
# imf = synthetic_not_applicable
# stellar_mass_range = synthetic_not_applicable
# solar_abundance_reference = synthetic_not_applicable
# production_calibrated = false
# hash_scope = UTF-8 data rows only, including final newline
# columns = Z age_yr return_total total_ejected_metals newly_synthesized_metals events energy_erg return_winds_agb return_ccsn return_snia metals_winds_agb metals_ccsn metals_snia new_metals_winds_agb new_metals_ccsn new_metals_snia events_winds_agb events_ccsn events_snia energy_winds_agb energy_ccsn energy_snia
"""
    return header + payload


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("resources/stellar_evolution/test_synthetic_v2.txt"),
    )
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
