function(cosmosim_bool_to_json INPUT_VALUE OUTPUT_VAR)
  if(${INPUT_VALUE})
    set(${OUTPUT_VAR} "true" PARENT_SCOPE)
  else()
    set(${OUTPUT_VAR} "false" PARENT_SCOPE)
  endif()
endfunction()

function(cosmosim_dependency_version DEFAULT_VALUE OUTPUT_VAR)
  if(ARGC GREATER 2)
    set(dep_var "${ARGV2}")
    if(DEFINED ${dep_var} AND NOT "${${dep_var}}" STREQUAL "")
      set(${OUTPUT_VAR} "${${dep_var}}" PARENT_SCOPE)
      return()
    endif()
  endif()
  set(${OUTPUT_VAR} "${DEFAULT_VALUE}" PARENT_SCOPE)
endfunction()

function(cosmosim_generate_feature_summary)
  set(options)
  set(one_value_args OUTPUT_TEXT OUTPUT_JSON)
  set(multi_value_args TARGETS)
  cmake_parse_arguments(COSMOSIM_SUMMARY "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

  if(NOT COSMOSIM_SUMMARY_OUTPUT_TEXT OR NOT COSMOSIM_SUMMARY_OUTPUT_JSON)
    message(FATAL_ERROR "cosmosim_generate_feature_summary requires OUTPUT_TEXT and OUTPUT_JSON")
  endif()

  cosmosim_bool_to_json(COSMOSIM_ENABLE_MPI feature_mpi)
  cosmosim_bool_to_json(COSMOSIM_ENABLE_HDF5 feature_hdf5)
  cosmosim_bool_to_json(COSMOSIM_ENABLE_FFTW feature_fftw)
  cosmosim_bool_to_json(COSMOSIM_ENABLE_CUDA feature_cuda)
  cosmosim_bool_to_json(COSMOSIM_ENABLE_PYTHON feature_python)
  cosmosim_bool_to_json(COSMOSIM_ENABLE_TESTS feature_tests)
  cosmosim_bool_to_json(COSMOSIM_ENABLE_BENCHMARKS feature_benchmarks)
  cosmosim_bool_to_json(COSMOSIM_ENABLE_LTO feature_lto)

  cosmosim_dependency_version("disabled" dep_mpi_version MPI_CXX_VERSION)
  cosmosim_dependency_version("disabled" dep_hdf5_version HDF5_VERSION)
  cosmosim_dependency_version("disabled" dep_fftw_version FFTW_VERSION)
  cosmosim_dependency_version("disabled" dep_cuda_toolkit_version CUDAToolkit_VERSION)
  cosmosim_dependency_version("disabled" dep_python_version Python3_VERSION)

  string(REPLACE ";" ", " target_list_readable "${COSMOSIM_SUMMARY_TARGETS}")
  string(REPLACE ";" "\",\n    \"" target_list_json "${COSMOSIM_SUMMARY_TARGETS}")

  set(summary_text "")
  string(APPEND summary_text "project=${PROJECT_NAME}\n")
  string(APPEND summary_text "version=${PROJECT_VERSION}\n")
  string(APPEND summary_text "preset=${COSMOSIM_SELECTED_PRESET}\n")
  string(APPEND summary_text "build_type=${CMAKE_BUILD_TYPE}\n")
  string(APPEND summary_text "cxx_compiler=${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}\n")
  string(APPEND summary_text "cxx_flags=${CMAKE_CXX_FLAGS}\n")
  string(APPEND summary_text "cxx_flags_debug=${CMAKE_CXX_FLAGS_DEBUG}\n")
  string(APPEND summary_text "cxx_flags_release=${CMAKE_CXX_FLAGS_RELEASE}\n")
  string(APPEND summary_text "feature_mpi=${feature_mpi}\n")
  string(APPEND summary_text "feature_hdf5=${feature_hdf5}\n")
  string(APPEND summary_text "feature_fftw=${feature_fftw}\n")
  string(APPEND summary_text "feature_cuda=${feature_cuda}\n")
  string(APPEND summary_text "feature_python=${feature_python}\n")
  string(APPEND summary_text "feature_tests=${feature_tests}\n")
  string(APPEND summary_text "feature_benchmarks=${feature_benchmarks}\n")
  string(APPEND summary_text "feature_lto=${feature_lto}\n")
  string(APPEND summary_text "dependency_mpi=${dep_mpi_version}\n")
  string(APPEND summary_text "dependency_hdf5=${dep_hdf5_version}\n")
  string(APPEND summary_text "dependency_fftw=${dep_fftw_version}\n")
  string(APPEND summary_text "dependency_cuda=${dep_cuda_toolkit_version}\n")
  string(APPEND summary_text "dependency_python=${dep_python_version}\n")
  string(APPEND summary_text "targets=${target_list_readable}\n")

  file(WRITE "${COSMOSIM_SUMMARY_OUTPUT_TEXT}" "${summary_text}")

  set(json_content "")
  string(APPEND json_content "{\n")
  string(APPEND json_content "  \"project\": \"${PROJECT_NAME}\",\n")
  string(APPEND json_content "  \"version\": \"${PROJECT_VERSION}\",\n")
  string(APPEND json_content "  \"preset\": \"${COSMOSIM_SELECTED_PRESET}\",\n")
  string(APPEND json_content "  \"generator\": \"${CMAKE_GENERATOR}\",\n")
  string(APPEND json_content "  \"build_type\": \"${CMAKE_BUILD_TYPE}\",\n")
  string(APPEND json_content "  \"compiler\": {\n")
  string(APPEND json_content "    \"id\": \"${CMAKE_CXX_COMPILER_ID}\",\n")
  string(APPEND json_content "    \"version\": \"${CMAKE_CXX_COMPILER_VERSION}\"\n")
  string(APPEND json_content "  },\n")
  string(APPEND json_content "  \"flags\": {\n")
  string(APPEND json_content "    \"common\": \"${CMAKE_CXX_FLAGS}\",\n")
  string(APPEND json_content "    \"debug\": \"${CMAKE_CXX_FLAGS_DEBUG}\",\n")
  string(APPEND json_content "    \"release\": \"${CMAKE_CXX_FLAGS_RELEASE}\"\n")
  string(APPEND json_content "  },\n")
  string(APPEND json_content "  \"features\": {\n")
  string(APPEND json_content "    \"mpi\": ${feature_mpi},\n")
  string(APPEND json_content "    \"hdf5\": ${feature_hdf5},\n")
  string(APPEND json_content "    \"fftw\": ${feature_fftw},\n")
  string(APPEND json_content "    \"cuda\": ${feature_cuda},\n")
  string(APPEND json_content "    \"python\": ${feature_python},\n")
  string(APPEND json_content "    \"tests\": ${feature_tests},\n")
  string(APPEND json_content "    \"benchmarks\": ${feature_benchmarks},\n")
  string(APPEND json_content "    \"lto\": ${feature_lto}\n")
  string(APPEND json_content "  },\n")
  string(APPEND json_content "  \"dependencies\": {\n")
  string(APPEND json_content "    \"mpi\": \"${dep_mpi_version}\",\n")
  string(APPEND json_content "    \"hdf5\": \"${dep_hdf5_version}\",\n")
  string(APPEND json_content "    \"fftw\": \"${dep_fftw_version}\",\n")
  string(APPEND json_content "    \"cuda_toolkit\": \"${dep_cuda_toolkit_version}\",\n")
  string(APPEND json_content "    \"python\": \"${dep_python_version}\"\n")
  string(APPEND json_content "  },\n")
  string(APPEND json_content "  \"targets\": [\n    \"${target_list_json}\"\n  ]\n")
  string(APPEND json_content "}\n")

  file(WRITE "${COSMOSIM_SUMMARY_OUTPUT_JSON}" "${json_content}")
endfunction()
